const ThemeActionTypes = {
	RESET_THEME:                'RESET_THEME',
	SET_PRIMARY_COLOUR:         'SET_PRIMARY_COLOUR',
	SET_SECONDARY_COLOUR:       'SET_SECONDARY_COLOUR',
	SET_PRIMARY_BTN_BG:         'SET_PRIMARY_BTN_BG',
	SET_PRIMARY_BTN_BG_HOVER:   'SET_PRIMARY_BTN_BG_HOVER',
	SET_PRIMARY_BTN_TEXT:       'SET_PRIMARY_BTN_TEXT',
	SET_PRIMARY_BTN_TEXT_HOVER: 'SET_PRIMARY_BTN_TEXT_HOVER'
}

export default ThemeActionTypes;